/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package blood0cean.com.github.office.schedule.model.impl;

import blood0cean.com.github.office.schedule.model.Office;
import blood0cean.com.github.office.schedule.model.OfficeModel;
import blood0cean.com.github.office.schedule.model.OfficeSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Office service. Represents a row in the &quot;OFFICE_Office&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OfficeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OfficeImpl}.
 * </p>
 *
 * @author Blood 0cean
 * @see OfficeImpl
 * @generated
 */
@JSON(strict = true)
public class OfficeModelImpl
	extends BaseModelImpl<Office> implements OfficeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a office model instance should use the <code>Office</code> interface instead.
	 */
	public static final String TABLE_NAME = "OFFICE_Office";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"officeId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"active_", Types.BOOLEAN}, {"maxPeopleAllowed", Types.INTEGER},
		{"availableFrom", Types.TIMESTAMP}, {"availableUntil", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("officeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("maxPeopleAllowed", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("availableFrom", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("availableUntil", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OFFICE_Office (uuid_ VARCHAR(75) null,officeId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,description VARCHAR(75) null,active_ BOOLEAN,maxPeopleAllowed INTEGER,availableFrom DATE null,availableUntil DATE null)";

	public static final String TABLE_SQL_DROP = "drop table OFFICE_Office";

	public static final String ORDER_BY_JPQL = " ORDER BY office.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OFFICE_Office.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	public static final long AVAILABLEFROM_COLUMN_BITMASK = 2L;

	public static final long AVAILABLEUNTIL_COLUMN_BITMASK = 4L;

	public static final long COMPANYID_COLUMN_BITMASK = 8L;

	public static final long GROUPID_COLUMN_BITMASK = 16L;

	public static final long NAME_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Office toModel(OfficeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Office model = new OfficeImpl();

		model.setUuid(soapModel.getUuid());
		model.setOfficeId(soapModel.getOfficeId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setActive(soapModel.isActive());
		model.setMaxPeopleAllowed(soapModel.getMaxPeopleAllowed());
		model.setAvailableFrom(soapModel.getAvailableFrom());
		model.setAvailableUntil(soapModel.getAvailableUntil());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Office> toModels(OfficeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Office> models = new ArrayList<Office>(soapModels.length);

		for (OfficeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public OfficeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _officeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOfficeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _officeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Office.class;
	}

	@Override
	public String getModelClassName() {
		return Office.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Office, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Office, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Office, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Office)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Office, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Office, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Office)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Office, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Office, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Office>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Office.class.getClassLoader(), Office.class, ModelWrapper.class);

		try {
			Constructor<Office> constructor =
				(Constructor<Office>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Office, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Office, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Office, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Office, Object>>();
		Map<String, BiConsumer<Office, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Office, ?>>();

		attributeGetterFunctions.put("uuid", Office::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Office, String>)Office::setUuid);
		attributeGetterFunctions.put("officeId", Office::getOfficeId);
		attributeSetterBiConsumers.put(
			"officeId", (BiConsumer<Office, Long>)Office::setOfficeId);
		attributeGetterFunctions.put("groupId", Office::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Office, Long>)Office::setGroupId);
		attributeGetterFunctions.put("companyId", Office::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Office, Long>)Office::setCompanyId);
		attributeGetterFunctions.put("userId", Office::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Office, Long>)Office::setUserId);
		attributeGetterFunctions.put("userName", Office::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Office, String>)Office::setUserName);
		attributeGetterFunctions.put("createDate", Office::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Office, Date>)Office::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Office::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Office, Date>)Office::setModifiedDate);
		attributeGetterFunctions.put("name", Office::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Office, String>)Office::setName);
		attributeGetterFunctions.put("description", Office::getDescription);
		attributeSetterBiConsumers.put(
			"description", (BiConsumer<Office, String>)Office::setDescription);
		attributeGetterFunctions.put("active", Office::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<Office, Boolean>)Office::setActive);
		attributeGetterFunctions.put(
			"maxPeopleAllowed", Office::getMaxPeopleAllowed);
		attributeSetterBiConsumers.put(
			"maxPeopleAllowed",
			(BiConsumer<Office, Integer>)Office::setMaxPeopleAllowed);
		attributeGetterFunctions.put("availableFrom", Office::getAvailableFrom);
		attributeSetterBiConsumers.put(
			"availableFrom",
			(BiConsumer<Office, Date>)Office::setAvailableFrom);
		attributeGetterFunctions.put(
			"availableUntil", Office::getAvailableUntil);
		attributeSetterBiConsumers.put(
			"availableUntil",
			(BiConsumer<Office, Date>)Office::setAvailableUntil);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getOfficeId() {
		return _officeId;
	}

	@Override
	public void setOfficeId(long officeId) {
		_officeId = officeId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@JSON
	@Override
	public int getMaxPeopleAllowed() {
		return _maxPeopleAllowed;
	}

	@Override
	public void setMaxPeopleAllowed(int maxPeopleAllowed) {
		_maxPeopleAllowed = maxPeopleAllowed;
	}

	@JSON
	@Override
	public Date getAvailableFrom() {
		return _availableFrom;
	}

	@Override
	public void setAvailableFrom(Date availableFrom) {
		_columnBitmask |= AVAILABLEFROM_COLUMN_BITMASK;

		if (_originalAvailableFrom == null) {
			_originalAvailableFrom = _availableFrom;
		}

		_availableFrom = availableFrom;
	}

	public Date getOriginalAvailableFrom() {
		return _originalAvailableFrom;
	}

	@JSON
	@Override
	public Date getAvailableUntil() {
		return _availableUntil;
	}

	@Override
	public void setAvailableUntil(Date availableUntil) {
		_columnBitmask |= AVAILABLEUNTIL_COLUMN_BITMASK;

		if (_originalAvailableUntil == null) {
			_originalAvailableUntil = _availableUntil;
		}

		_availableUntil = availableUntil;
	}

	public Date getOriginalAvailableUntil() {
		return _originalAvailableUntil;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Office.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Office.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Office toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Office>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OfficeImpl officeImpl = new OfficeImpl();

		officeImpl.setUuid(getUuid());
		officeImpl.setOfficeId(getOfficeId());
		officeImpl.setGroupId(getGroupId());
		officeImpl.setCompanyId(getCompanyId());
		officeImpl.setUserId(getUserId());
		officeImpl.setUserName(getUserName());
		officeImpl.setCreateDate(getCreateDate());
		officeImpl.setModifiedDate(getModifiedDate());
		officeImpl.setName(getName());
		officeImpl.setDescription(getDescription());
		officeImpl.setActive(isActive());
		officeImpl.setMaxPeopleAllowed(getMaxPeopleAllowed());
		officeImpl.setAvailableFrom(getAvailableFrom());
		officeImpl.setAvailableUntil(getAvailableUntil());

		officeImpl.resetOriginalValues();

		return officeImpl;
	}

	@Override
	public int compareTo(Office office) {
		int value = 0;

		value = getName().compareTo(office.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Office)) {
			return false;
		}

		Office office = (Office)obj;

		long primaryKey = office.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		OfficeModelImpl officeModelImpl = this;

		officeModelImpl._originalUuid = officeModelImpl._uuid;

		officeModelImpl._originalGroupId = officeModelImpl._groupId;

		officeModelImpl._setOriginalGroupId = false;

		officeModelImpl._originalCompanyId = officeModelImpl._companyId;

		officeModelImpl._setOriginalCompanyId = false;

		officeModelImpl._setModifiedDate = false;

		officeModelImpl._originalName = officeModelImpl._name;

		officeModelImpl._originalActive = officeModelImpl._active;

		officeModelImpl._setOriginalActive = false;

		officeModelImpl._originalAvailableFrom = officeModelImpl._availableFrom;

		officeModelImpl._originalAvailableUntil =
			officeModelImpl._availableUntil;

		officeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Office> toCacheModel() {
		OfficeCacheModel officeCacheModel = new OfficeCacheModel();

		officeCacheModel.uuid = getUuid();

		String uuid = officeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			officeCacheModel.uuid = null;
		}

		officeCacheModel.officeId = getOfficeId();

		officeCacheModel.groupId = getGroupId();

		officeCacheModel.companyId = getCompanyId();

		officeCacheModel.userId = getUserId();

		officeCacheModel.userName = getUserName();

		String userName = officeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			officeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			officeCacheModel.createDate = createDate.getTime();
		}
		else {
			officeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			officeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			officeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		officeCacheModel.name = getName();

		String name = officeCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			officeCacheModel.name = null;
		}

		officeCacheModel.description = getDescription();

		String description = officeCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			officeCacheModel.description = null;
		}

		officeCacheModel.active = isActive();

		officeCacheModel.maxPeopleAllowed = getMaxPeopleAllowed();

		Date availableFrom = getAvailableFrom();

		if (availableFrom != null) {
			officeCacheModel.availableFrom = availableFrom.getTime();
		}
		else {
			officeCacheModel.availableFrom = Long.MIN_VALUE;
		}

		Date availableUntil = getAvailableUntil();

		if (availableUntil != null) {
			officeCacheModel.availableUntil = availableUntil.getTime();
		}
		else {
			officeCacheModel.availableUntil = Long.MIN_VALUE;
		}

		return officeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Office, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Office, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Office, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Office)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Office, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Office, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Office, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Office)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Office>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _officeId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _description;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private int _maxPeopleAllowed;
	private Date _availableFrom;
	private Date _originalAvailableFrom;
	private Date _availableUntil;
	private Date _originalAvailableUntil;
	private long _columnBitmask;
	private Office _escapedModel;

}