/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package blood0cean.com.github.office.schedule.model.impl;

import blood0cean.com.github.office.schedule.model.OfficeSchedule;
import blood0cean.com.github.office.schedule.model.OfficeScheduleModel;
import blood0cean.com.github.office.schedule.model.OfficeScheduleSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OfficeSchedule service. Represents a row in the &quot;OFFICE_OfficeSchedule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OfficeScheduleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OfficeScheduleImpl}.
 * </p>
 *
 * @author Blood 0cean
 * @see OfficeScheduleImpl
 * @generated
 */
@JSON(strict = true)
public class OfficeScheduleModelImpl
	extends BaseModelImpl<OfficeSchedule> implements OfficeScheduleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a office schedule model instance should use the <code>OfficeSchedule</code> interface instead.
	 */
	public static final String TABLE_NAME = "OFFICE_OfficeSchedule";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"officeScheduleId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"officeId", Types.BIGINT}, {"spots", Types.INTEGER},
		{"date_", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("officeScheduleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("officeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("spots", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("date_", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OFFICE_OfficeSchedule (uuid_ VARCHAR(75) null,officeScheduleId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,officeId LONG,spots INTEGER,date_ DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table OFFICE_OfficeSchedule";

	public static final String ORDER_BY_JPQL =
		" ORDER BY officeSchedule.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OFFICE_OfficeSchedule.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long OFFICEID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static OfficeSchedule toModel(OfficeScheduleSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		OfficeSchedule model = new OfficeScheduleImpl();

		model.setUuid(soapModel.getUuid());
		model.setOfficeScheduleId(soapModel.getOfficeScheduleId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setOfficeId(soapModel.getOfficeId());
		model.setSpots(soapModel.getSpots());
		model.setDate(soapModel.getDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<OfficeSchedule> toModels(
		OfficeScheduleSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<OfficeSchedule> models = new ArrayList<OfficeSchedule>(
			soapModels.length);

		for (OfficeScheduleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public OfficeScheduleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _officeScheduleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOfficeScheduleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _officeScheduleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OfficeSchedule.class;
	}

	@Override
	public String getModelClassName() {
		return OfficeSchedule.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OfficeSchedule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OfficeSchedule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OfficeSchedule, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((OfficeSchedule)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OfficeSchedule, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OfficeSchedule, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OfficeSchedule)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OfficeSchedule, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OfficeSchedule, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, OfficeSchedule>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			OfficeSchedule.class.getClassLoader(), OfficeSchedule.class,
			ModelWrapper.class);

		try {
			Constructor<OfficeSchedule> constructor =
				(Constructor<OfficeSchedule>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<OfficeSchedule, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OfficeSchedule, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OfficeSchedule, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<OfficeSchedule, Object>>();
		Map<String, BiConsumer<OfficeSchedule, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<OfficeSchedule, ?>>();

		attributeGetterFunctions.put("uuid", OfficeSchedule::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<OfficeSchedule, String>)OfficeSchedule::setUuid);
		attributeGetterFunctions.put(
			"officeScheduleId", OfficeSchedule::getOfficeScheduleId);
		attributeSetterBiConsumers.put(
			"officeScheduleId",
			(BiConsumer<OfficeSchedule, Long>)
				OfficeSchedule::setOfficeScheduleId);
		attributeGetterFunctions.put("groupId", OfficeSchedule::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<OfficeSchedule, Long>)OfficeSchedule::setGroupId);
		attributeGetterFunctions.put("companyId", OfficeSchedule::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<OfficeSchedule, Long>)OfficeSchedule::setCompanyId);
		attributeGetterFunctions.put("userId", OfficeSchedule::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<OfficeSchedule, Long>)OfficeSchedule::setUserId);
		attributeGetterFunctions.put("userName", OfficeSchedule::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<OfficeSchedule, String>)OfficeSchedule::setUserName);
		attributeGetterFunctions.put(
			"createDate", OfficeSchedule::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<OfficeSchedule, Date>)OfficeSchedule::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", OfficeSchedule::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<OfficeSchedule, Date>)OfficeSchedule::setModifiedDate);
		attributeGetterFunctions.put("officeId", OfficeSchedule::getOfficeId);
		attributeSetterBiConsumers.put(
			"officeId",
			(BiConsumer<OfficeSchedule, Long>)OfficeSchedule::setOfficeId);
		attributeGetterFunctions.put("spots", OfficeSchedule::getSpots);
		attributeSetterBiConsumers.put(
			"spots",
			(BiConsumer<OfficeSchedule, Integer>)OfficeSchedule::setSpots);
		attributeGetterFunctions.put("date", OfficeSchedule::getDate);
		attributeSetterBiConsumers.put(
			"date", (BiConsumer<OfficeSchedule, Date>)OfficeSchedule::setDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getOfficeScheduleId() {
		return _officeScheduleId;
	}

	@Override
	public void setOfficeScheduleId(long officeScheduleId) {
		_officeScheduleId = officeScheduleId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getOfficeId() {
		return _officeId;
	}

	@Override
	public void setOfficeId(long officeId) {
		_columnBitmask |= OFFICEID_COLUMN_BITMASK;

		if (!_setOriginalOfficeId) {
			_setOriginalOfficeId = true;

			_originalOfficeId = _officeId;
		}

		_officeId = officeId;
	}

	public long getOriginalOfficeId() {
		return _originalOfficeId;
	}

	@JSON
	@Override
	public int getSpots() {
		return _spots;
	}

	@Override
	public void setSpots(int spots) {
		_spots = spots;
	}

	@JSON
	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		_date = date;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(OfficeSchedule.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), OfficeSchedule.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OfficeSchedule toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OfficeSchedule>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OfficeScheduleImpl officeScheduleImpl = new OfficeScheduleImpl();

		officeScheduleImpl.setUuid(getUuid());
		officeScheduleImpl.setOfficeScheduleId(getOfficeScheduleId());
		officeScheduleImpl.setGroupId(getGroupId());
		officeScheduleImpl.setCompanyId(getCompanyId());
		officeScheduleImpl.setUserId(getUserId());
		officeScheduleImpl.setUserName(getUserName());
		officeScheduleImpl.setCreateDate(getCreateDate());
		officeScheduleImpl.setModifiedDate(getModifiedDate());
		officeScheduleImpl.setOfficeId(getOfficeId());
		officeScheduleImpl.setSpots(getSpots());
		officeScheduleImpl.setDate(getDate());

		officeScheduleImpl.resetOriginalValues();

		return officeScheduleImpl;
	}

	@Override
	public int compareTo(OfficeSchedule officeSchedule) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), officeSchedule.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof OfficeSchedule)) {
			return false;
		}

		OfficeSchedule officeSchedule = (OfficeSchedule)obj;

		long primaryKey = officeSchedule.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		OfficeScheduleModelImpl officeScheduleModelImpl = this;

		officeScheduleModelImpl._originalUuid = officeScheduleModelImpl._uuid;

		officeScheduleModelImpl._originalGroupId =
			officeScheduleModelImpl._groupId;

		officeScheduleModelImpl._setOriginalGroupId = false;

		officeScheduleModelImpl._originalCompanyId =
			officeScheduleModelImpl._companyId;

		officeScheduleModelImpl._setOriginalCompanyId = false;

		officeScheduleModelImpl._setModifiedDate = false;

		officeScheduleModelImpl._originalOfficeId =
			officeScheduleModelImpl._officeId;

		officeScheduleModelImpl._setOriginalOfficeId = false;

		officeScheduleModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<OfficeSchedule> toCacheModel() {
		OfficeScheduleCacheModel officeScheduleCacheModel =
			new OfficeScheduleCacheModel();

		officeScheduleCacheModel.uuid = getUuid();

		String uuid = officeScheduleCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			officeScheduleCacheModel.uuid = null;
		}

		officeScheduleCacheModel.officeScheduleId = getOfficeScheduleId();

		officeScheduleCacheModel.groupId = getGroupId();

		officeScheduleCacheModel.companyId = getCompanyId();

		officeScheduleCacheModel.userId = getUserId();

		officeScheduleCacheModel.userName = getUserName();

		String userName = officeScheduleCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			officeScheduleCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			officeScheduleCacheModel.createDate = createDate.getTime();
		}
		else {
			officeScheduleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			officeScheduleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			officeScheduleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		officeScheduleCacheModel.officeId = getOfficeId();

		officeScheduleCacheModel.spots = getSpots();

		Date date = getDate();

		if (date != null) {
			officeScheduleCacheModel.date = date.getTime();
		}
		else {
			officeScheduleCacheModel.date = Long.MIN_VALUE;
		}

		return officeScheduleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OfficeSchedule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OfficeSchedule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OfficeSchedule, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((OfficeSchedule)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<OfficeSchedule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<OfficeSchedule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OfficeSchedule, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((OfficeSchedule)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OfficeSchedule>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _officeScheduleId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _officeId;
	private long _originalOfficeId;
	private boolean _setOriginalOfficeId;
	private int _spots;
	private Date _date;
	private long _columnBitmask;
	private OfficeSchedule _escapedModel;

}