/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package blood0cean.com.github.office.schedule.service.base;

import blood0cean.com.github.office.schedule.model.OfficeSchedule;
import blood0cean.com.github.office.schedule.service.OfficeScheduleLocalService;
import blood0cean.com.github.office.schedule.service.persistence.OfficePersistence;
import blood0cean.com.github.office.schedule.service.persistence.OfficeSchedulePersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the office schedule local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link blood0cean.com.github.office.schedule.service.impl.OfficeScheduleLocalServiceImpl}.
 * </p>
 *
 * @author Blood 0cean
 * @see blood0cean.com.github.office.schedule.service.impl.OfficeScheduleLocalServiceImpl
 * @generated
 */
public abstract class OfficeScheduleLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, OfficeScheduleLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>OfficeScheduleLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>blood0cean.com.github.office.schedule.service.OfficeScheduleLocalServiceUtil</code>.
	 */

	/**
	 * Adds the office schedule to the database. Also notifies the appropriate model listeners.
	 *
	 * @param officeSchedule the office schedule
	 * @return the office schedule that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public OfficeSchedule addOfficeSchedule(OfficeSchedule officeSchedule) {
		officeSchedule.setNew(true);

		return officeSchedulePersistence.update(officeSchedule);
	}

	/**
	 * Creates a new office schedule with the primary key. Does not add the office schedule to the database.
	 *
	 * @param officeScheduleId the primary key for the new office schedule
	 * @return the new office schedule
	 */
	@Override
	@Transactional(enabled = false)
	public OfficeSchedule createOfficeSchedule(long officeScheduleId) {
		return officeSchedulePersistence.create(officeScheduleId);
	}

	/**
	 * Deletes the office schedule with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param officeScheduleId the primary key of the office schedule
	 * @return the office schedule that was removed
	 * @throws PortalException if a office schedule with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public OfficeSchedule deleteOfficeSchedule(long officeScheduleId)
		throws PortalException {

		return officeSchedulePersistence.remove(officeScheduleId);
	}

	/**
	 * Deletes the office schedule from the database. Also notifies the appropriate model listeners.
	 *
	 * @param officeSchedule the office schedule
	 * @return the office schedule that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public OfficeSchedule deleteOfficeSchedule(OfficeSchedule officeSchedule) {
		return officeSchedulePersistence.remove(officeSchedule);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			OfficeSchedule.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return officeSchedulePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>blood0cean.com.github.office.schedule.model.impl.OfficeScheduleModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return officeSchedulePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>blood0cean.com.github.office.schedule.model.impl.OfficeScheduleModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return officeSchedulePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return officeSchedulePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return officeSchedulePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public OfficeSchedule fetchOfficeSchedule(long officeScheduleId) {
		return officeSchedulePersistence.fetchByPrimaryKey(officeScheduleId);
	}

	/**
	 * Returns the office schedule matching the UUID and group.
	 *
	 * @param uuid the office schedule's UUID
	 * @param groupId the primary key of the group
	 * @return the matching office schedule, or <code>null</code> if a matching office schedule could not be found
	 */
	@Override
	public OfficeSchedule fetchOfficeScheduleByUuidAndGroupId(
		String uuid, long groupId) {

		return officeSchedulePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the office schedule with the primary key.
	 *
	 * @param officeScheduleId the primary key of the office schedule
	 * @return the office schedule
	 * @throws PortalException if a office schedule with the primary key could not be found
	 */
	@Override
	public OfficeSchedule getOfficeSchedule(long officeScheduleId)
		throws PortalException {

		return officeSchedulePersistence.findByPrimaryKey(officeScheduleId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(officeScheduleLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(OfficeSchedule.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("officeScheduleId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			officeScheduleLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(OfficeSchedule.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"officeScheduleId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(officeScheduleLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(OfficeSchedule.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("officeScheduleId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<OfficeSchedule>() {

				@Override
				public void performAction(OfficeSchedule officeSchedule)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, officeSchedule);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(OfficeSchedule.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return officeScheduleLocalService.deleteOfficeSchedule(
			(OfficeSchedule)persistedModel);
	}

	public BasePersistence<OfficeSchedule> getBasePersistence() {
		return officeSchedulePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return officeSchedulePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the office schedules matching the UUID and company.
	 *
	 * @param uuid the UUID of the office schedules
	 * @param companyId the primary key of the company
	 * @return the matching office schedules, or an empty list if no matches were found
	 */
	@Override
	public List<OfficeSchedule> getOfficeSchedulesByUuidAndCompanyId(
		String uuid, long companyId) {

		return officeSchedulePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of office schedules matching the UUID and company.
	 *
	 * @param uuid the UUID of the office schedules
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of office schedules
	 * @param end the upper bound of the range of office schedules (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching office schedules, or an empty list if no matches were found
	 */
	@Override
	public List<OfficeSchedule> getOfficeSchedulesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<OfficeSchedule> orderByComparator) {

		return officeSchedulePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the office schedule matching the UUID and group.
	 *
	 * @param uuid the office schedule's UUID
	 * @param groupId the primary key of the group
	 * @return the matching office schedule
	 * @throws PortalException if a matching office schedule could not be found
	 */
	@Override
	public OfficeSchedule getOfficeScheduleByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return officeSchedulePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the office schedules.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>blood0cean.com.github.office.schedule.model.impl.OfficeScheduleModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of office schedules
	 * @param end the upper bound of the range of office schedules (not inclusive)
	 * @return the range of office schedules
	 */
	@Override
	public List<OfficeSchedule> getOfficeSchedules(int start, int end) {
		return officeSchedulePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of office schedules.
	 *
	 * @return the number of office schedules
	 */
	@Override
	public int getOfficeSchedulesCount() {
		return officeSchedulePersistence.countAll();
	}

	/**
	 * Updates the office schedule in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param officeSchedule the office schedule
	 * @return the office schedule that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public OfficeSchedule updateOfficeSchedule(OfficeSchedule officeSchedule) {
		return officeSchedulePersistence.update(officeSchedule);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			OfficeScheduleLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		officeScheduleLocalService = (OfficeScheduleLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return OfficeScheduleLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return OfficeSchedule.class;
	}

	protected String getModelClassName() {
		return OfficeSchedule.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = officeSchedulePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected OfficePersistence officePersistence;

	protected OfficeScheduleLocalService officeScheduleLocalService;

	@Reference
	protected OfficeSchedulePersistence officeSchedulePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}