/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package blood0cean.com.github.office.schedule.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the OfficeSchedule service. Represents a row in the &quot;OFFICE_OfficeSchedule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>blood0cean.com.github.office.schedule.model.impl.OfficeScheduleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>blood0cean.com.github.office.schedule.model.impl.OfficeScheduleImpl</code>.
 * </p>
 *
 * @author Blood 0cean
 * @see OfficeSchedule
 * @generated
 */
@ProviderType
public interface OfficeScheduleModel
	extends BaseModel<OfficeSchedule>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a office schedule model instance should use the {@link OfficeSchedule} interface instead.
	 */

	/**
	 * Returns the primary key of this office schedule.
	 *
	 * @return the primary key of this office schedule
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this office schedule.
	 *
	 * @param primaryKey the primary key of this office schedule
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this office schedule.
	 *
	 * @return the uuid of this office schedule
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this office schedule.
	 *
	 * @param uuid the uuid of this office schedule
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the office schedule ID of this office schedule.
	 *
	 * @return the office schedule ID of this office schedule
	 */
	public long getOfficeScheduleId();

	/**
	 * Sets the office schedule ID of this office schedule.
	 *
	 * @param officeScheduleId the office schedule ID of this office schedule
	 */
	public void setOfficeScheduleId(long officeScheduleId);

	/**
	 * Returns the group ID of this office schedule.
	 *
	 * @return the group ID of this office schedule
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this office schedule.
	 *
	 * @param groupId the group ID of this office schedule
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this office schedule.
	 *
	 * @return the company ID of this office schedule
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this office schedule.
	 *
	 * @param companyId the company ID of this office schedule
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this office schedule.
	 *
	 * @return the user ID of this office schedule
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this office schedule.
	 *
	 * @param userId the user ID of this office schedule
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this office schedule.
	 *
	 * @return the user uuid of this office schedule
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this office schedule.
	 *
	 * @param userUuid the user uuid of this office schedule
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this office schedule.
	 *
	 * @return the user name of this office schedule
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this office schedule.
	 *
	 * @param userName the user name of this office schedule
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this office schedule.
	 *
	 * @return the create date of this office schedule
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this office schedule.
	 *
	 * @param createDate the create date of this office schedule
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this office schedule.
	 *
	 * @return the modified date of this office schedule
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this office schedule.
	 *
	 * @param modifiedDate the modified date of this office schedule
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the office ID of this office schedule.
	 *
	 * @return the office ID of this office schedule
	 */
	public long getOfficeId();

	/**
	 * Sets the office ID of this office schedule.
	 *
	 * @param officeId the office ID of this office schedule
	 */
	public void setOfficeId(long officeId);

	/**
	 * Returns the spots of this office schedule.
	 *
	 * @return the spots of this office schedule
	 */
	public int getSpots();

	/**
	 * Sets the spots of this office schedule.
	 *
	 * @param spots the spots of this office schedule
	 */
	public void setSpots(int spots);

	/**
	 * Returns the date of this office schedule.
	 *
	 * @return the date of this office schedule
	 */
	public Date getDate();

	/**
	 * Sets the date of this office schedule.
	 *
	 * @param date the date of this office schedule
	 */
	public void setDate(Date date);

}